#!/bin/sh

rm -fr .venv || true

python=python3
[ -f ~/opt/cpython/bin/python3.12 ] && python=~/opt/cpython/bin/python3.12

hash -r
echo python=${python}

$python -m venv .venv

. ./.venv/bin/activate

python3 -m pip install --upgrade pip wheel

pip install -r ./requirements.txt

pip install -r ./requirements.dev.txt
