version: '3.8'
services:
  piday2024:
    environment:
      TZ: PST8PDT
    restart: unless-stopped
    ports:
      - 9000:9000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
