version: '3.8'
services:
  piday2024:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
